services:
  db:
    image: mariadb:latest
    container_name: lockbox-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "9000:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 5555:8000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
networks:
  backend:
    driver: bridge